export const gdmModules: string[][] = [
  ['gdm', 'authList'],
  ['gdm', 'authPrompt'],
  ['gdm', 'batch'],
  ['gdm', 'credentialManager'],
  ['gdm', 'loginDialog'],
  ['gdm', 'oVirt'],
  ['gdm', 'realmd'],
  ['gdm', 'util'],
  ['gdm', 'vmware'],
];

export const miscModules: string[][] = [
  ['misc', 'config'],
  ['misc', 'dbusUtils'],
  ['misc', 'extensionUtils'],
  ['misc', 'fileUtils'],
  ['misc', 'gnomeSession'],
  ['misc', 'history'],
  ['misc', 'ibusManager'],
  ['misc', 'inputMethod'],
  ['misc', 'introspect'],
  ['misc', 'jsParse'],
  ['misc', 'keyboardManager'],
  ['misc', 'loginManager'],
  ['misc', 'modemManager'],
  ['misc', 'objectManager'],
  ['misc', 'params'],
  ['misc', 'parentalControlsManager'],
  ['misc', 'permissionStore'],
  ['misc', 'signalTracker'],
  ['misc', 'signals'],
  ['misc', 'smartcardManager'],
  ['misc', 'systemActions'],
  ['misc', 'util'],
  ['misc', 'weather'],
];

export const perfModules: string[][] = [
  ['perf', 'basic'],
  ['perf', 'core'],
  ['perf', 'hwtest'],
];

export const uiModules: string[][] = [
  ['ui', 'accessDialog'],
  ['ui', 'altTab'],
  ['ui', 'animation'],
  ['ui', 'appDisplay'],
  ['ui', 'appFavorites'],
  ['ui', 'appMenu'],
  ['ui', 'audioDeviceSelection'],
  ['ui', 'background'],
  ['ui', 'backgroundMenu'],
  ['ui', 'barLevel'],
  ['ui', 'boxpointer'],
  ['ui', 'calendar'],
  ['ui', 'checkBox'],
  ['ui', 'closeDialog'],
  ['ui', 'ctrlAltTab'],
  ['ui', 'dash'],
  ['ui', 'dateMenu'],
  ['ui', 'dialog'],
  ['ui', 'dnd'],
  ['ui', 'edgeDragAction'],
  ['ui', 'endSessionDialog'],
  ['ui', 'environment'],
  ['ui', 'extensionDownloader'],
  ['ui', 'extensionSystem'],
  ['ui', 'focusCaretTracker'],
  ['ui', 'grabHelper'],
  ['ui', 'ibusCandidatePopup'],
  ['ui', 'iconGrid'],
  ['ui', 'inhibitShortcutsDialog'],
  ['ui', 'init'],
  ['ui', 'kbdA11yDialog'],
  ['ui', 'keyboard'],
  ['ui', 'layout'],
  ['ui', 'lightbox'],
  ['ui', 'locatePointer'],
  ['ui', 'lookingGlass'],
  ['ui', 'magnifier'],
  ['ui', 'main'],
  ['ui', 'messageList'],
  ['ui', 'messageTray'],
  ['ui', 'modalDialog'],
  ['ui', 'mpris'],
  ['ui', 'notificationDaemon'],
  ['ui', 'osdMonitorLabeler'],
  ['ui', 'osdWindow'],
  ['ui', 'overview'],
  ['ui', 'overviewControls'],
  ['ui', 'padOsd'],
  ['ui', 'pageIndicators'],
  ['ui', 'panel'],
  ['ui', 'panelMenu'],
  ['ui', 'pointerA11yTimeout'],
  ['ui', 'pointerWatcher'],
  ['ui', 'popupMenu'],
  ['ui', 'quickSettings'],
  ['ui', 'remoteSearch'],
  ['ui', 'ripples'],
  ['ui', 'runDialog'],
  ['ui', 'screenShield'],
  ['ui', 'screenshot'],
  ['ui', 'scripting'],
  ['ui', 'search'],
  ['ui', 'searchController'],
  ['ui', 'sessionMode'],
  ['ui', 'shellDBus'],
  ['ui', 'shellEntry'],
  ['ui', 'shellMountOperation'],
  ['ui', 'slider'],
  ['ui', 'swipeTracker'],
  ['ui', 'switchMonitor'],
  ['ui', 'switcherPopup'],
  ['ui', 'unlockDialog'],
  ['ui', 'userWidget'],
  ['ui', 'welcomeDialog'],
  ['ui', 'windowAttentionHandler'],
  ['ui', 'windowManager'],
  ['ui', 'windowMenu'],
  ['ui', 'windowPreview'],
  ['ui', 'workspace'],
  ['ui', 'workspaceAnimation'],
  ['ui', 'workspaceSwitcherPopup'],
  ['ui', 'workspaceThumbnail'],
  ['ui', 'workspacesView'],
  ['ui', 'xdndHandler'],
  ['ui', 'components', '__init__'],
  ['ui', 'components', 'automountManager'],
  ['ui', 'components', 'autorunManager'],
  ['ui', 'components', 'keyring'],
  ['ui', 'components', 'networkAgent'],
  ['ui', 'components', 'polkitAgent'],
  ['ui', 'components', 'telepathyClient'],
  ['ui', 'status', 'accessibility'],
  ['ui', 'status', 'autoRotate'],
  ['ui', 'status', 'bluetooth'],
  ['ui', 'status', 'brightness'],
  ['ui', 'status', 'darkMode'],
  ['ui', 'status', 'dwellClick'],
  ['ui', 'status', 'keyboard'],
  ['ui', 'status', 'location'],
  ['ui', 'status', 'network'],
  ['ui', 'status', 'nightLight'],
  ['ui', 'status', 'powerProfiles'],
  ['ui', 'status', 'remoteAccess'],
  ['ui', 'status', 'rfkill'],
  ['ui', 'status', 'system'],
  ['ui', 'status', 'thunderbolt'],
  ['ui', 'status', 'volume'],
];

export const giModules: string[][] = [
  ['gi', 'AccountsService'],
  ['gi', 'Adw'],
  ['gi', 'Atk'],
  ['gi', 'Atspi'],
  ['gi', 'cairo'],
  ['gi', 'Cally'],
  ['gi', 'Clutter'],
  ['gi', 'ClutterX11'],
  ['gi', 'Cogl'],
  ['gi', 'CoglPango'],
  ['gi', 'DBus'],
  ['gi', 'freetype2'],
  ['gi', 'Gck'],
  ['gi', 'Gcr'],
  ['gi', 'GDesktopEnums'],
  ['gi', 'Gdk'],
  ['gi', 'GdkPixbuf'],
  ['gi', 'Gdm'],
  ['gi', 'Geoclue'],
  ['gi', 'Gio'],
  ['gi', 'GIRepository'],
  ['gi', 'GLib'],
  ['gi', 'GModule'],
  ['gi', 'GnomeBluetooth'],
  ['gi', 'GnomeDesktop'],
  ['gi', 'GObject'],
  ['gi', 'Graphene'],
  ['gi', 'Gsk'],
  ['gi', 'Gst'],
  ['gi', 'Gtk'],
  ['gi', 'Gvc'],
  ['gi', 'GWeather'],
  ['gi', 'Handy'],
  ['gi', 'HarfBuzz'],
  ['gi', 'IBus'],
  ['gi', 'JavaScriptCore'],
  ['gi', 'Json'],
  ['gi', 'Malcontent'],
  ['gi', 'Meta'],
  ['gi', 'ModemManager'],
  ['gi', 'NM'],
  ['gi', 'NMA'],
  ['gi', 'Notify'],
  ['gi', 'Pango'],
  ['gi', 'PangoCairo'],
  ['gi', 'Polkit'],
  ['gi', 'PolkitAgent'],
  ['gi', 'Rsvg'],
  ['gi', 'Shell'],
  ['gi', 'Shew'],
  ['gi', 'Soup'],
  ['gi', 'St'],
  ['gi', 'TelepathyGLib'],
  ['gi', 'TelepathyLogger'],
  ['gi', 'UPowerGlib'],
  ['gi', 'WebKit2'],
  ['gi', 'WebKit2WebExtension'],
  ['gi', 'xfixes'],
  ['gi', 'xlib'],
];

export const defaultModules: string[][] = [
  ['cairo'],
];

const giURLs: string[] = [
  '@gi-types/accountsservice1',
  '@gi-types/adw1',
  '@gi-types/atk2',
  '@gi-types/atspi2',
  '@gi-types/cairo1',
  '@gi-types/cally10',
  '@gi-types/clutter10',
  '@gi-types/clutterx118',
  '@gi-types/cogl10',
  '@gi-types/coglpango10',
  '@gi-types/dbus1',
  '@gi-types/freetype22',
  '@gi-types/gck1',
  '@gi-types/gcr3',
  '@gi-types/gdesktopenums3',
  '@gi-types/gdk4',
  '@gi-types/gdkpixbuf2',
  '@gi-types/gdm1',
  '@gi-types/geoclue2',
  '@gi-types/gio2',
  '@gi-types/girepository2',
  '@gi-types/glib2',
  '@gi-types/gmodule2',
  '@gi-types/gnomebluetooth3',
  '@gi-types/gnomedesktop',
  '@gi-types/gobject2',
  '@gi-types/graphene1',
  '@gi-types/gsk4',
  '@gi-types/gst1',
  '@gi-types/gtk4',
  '@gi-types/gvc1',
  '@gi-types/gweather4',
  '@gi-types/handy1',
  '@gi-types/harfbuzz2',
  '@gi-types/ibus1',
  '@gi-types/javascriptcore4',
  '@gi-types/json1',
  '@gi-types/malcontent0',
  '@gi-types/meta10',
  '@gi-types/modemmanager1',
  '@gi-types/nm1',
  '@gi-types/nma1',
  '@gi-types/notify0',
  '@gi-types/pango1',
  '@gi-types/pangocairo1',
  '@gi-types/polkit1',
  '@gi-types/polkitagent1',
  '@gi-types/rsvg2',
  '@gi-types/shell0',
  '@gi-types/shew0',
  '@gi-types/soup3',
  '@gi-types/st1',
  '@gi-types/telepathyglib0',
  '@gi-types/telepathylogger0',
  '@gi-types/upowerglib1',
  '@gi-types/webkit24',
  '@gi-types/webkit2webextension4',
  '@gi-types/xfixes4',
  '@gi-types/xlib2',
];

const defaultURLs: string[] = [
  '@gi-types/cairo1'
];

export const gdmMap: Map<string, string> = new Map(gdmModules.map((key, _) => [key.join('/'), key.join('/')]));
export const miscMap: Map<string, string> = new Map(miscModules.map((key, _) => [key.join('/'), key.join('/')]));
export const perfMap: Map<string, string> = new Map(perfModules.map((key, _) => [key.join('/'), key.join('/')]));
export const uiMap: Map<string, string> = new Map(uiModules.map((key, _) => [key.join('/'), key.join('/')]));
export const giMap: Map<string, string> = new Map(giModules.map((key, index) => [key.join('/'), giURLs[index]]));
export const defaultMap: Map<string, string> = new Map(defaultModules.map((key, index) => [key.join('/'), defaultURLs[index]]));

export const domainsModulesMap: Map<string, {modules: string[][], map: Map<string, string>}> = new Map([
  ['', {modules: defaultModules, map: defaultMap}],
  ['gi', {modules: giModules, map: giMap}],
  ['gdm', {modules: gdmModules, map: gdmMap}],
  ['misc', {modules: miscModules, map: miscMap}],
  ['perf', {modules: perfModules, map: perfMap}],
  ['ui', {modules: uiModules, map: uiMap}],
]);
